import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube,} from "react-icons/ai"
import Image from "next/image";
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import coding from "../public/coding.jpg";
import headshot1 from "../public/headshot-1.jpg"
import headshot2 from "../public/headshot-2.jpg"
import headshot3 from "../public/headshot-3.jpg"
import action1 from "../public/action-1.jpg"
import action2 from "../public/action-2.jpg"
import action3 from "../public/action-3.jpg"


export default function Home() {
  return (
    <div>
      <>
        <Head>
          <title>Joshua Bomba</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className=' bg-gray-700 text-black px-10 dark:bg-gray-900 dark:text-white md:px-20 lg:px-40'>

          <section className='min-h-screen'>
            <nav className='py-10 mb-12 flex justify-end'>
              <ul className='flex items-center'>
                <li><a className='bg-gradient-to-r from-red-400 to-slate-500 text-white px-4 py-2 rounded-md ml-8' href="mailto:jbomba53@gmail.com">Email Me</a></li>
              </ul>
            </nav>
            <div className='text-center p-10'>
              <h2 className='text-5xl py-2 text-red-400 font-medium md:text-6xl'>Joshua Bomba</h2>
              <h3 className='text-2xl py-2 text-red-400 md:text-3xl'>Chicago Based Actor</h3>
              <p className='text-md py-5 leading-8 text-white dark:text-white md:text-xl max-w-xl mx-auto'>Local hire anywhere with a cheap hotel. Horror lover. 2006 Time Person of the Year. The best cat dad you will ever meet.</p>
            </div>
            <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-10 overflow-hidden md:h-96 md:w-96'>
              <Image alt='headshot of actor' src={headshot3} layout="fill" objectFit="cover"/>
            </div>
          </section>
          
          <section>
            <div>
              <h3 className='text-3xl text-white py-1'>Portfolio</h3>
              <p className='text-md py-2 leading-8 text-white dark:text-white'>A selection of some of my previous productions.</p>
            </div>
            <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap justify-center items-center'>
              <div><Image width={parseFloat('500%')} height={parseFloat('500%')} className='rounded-lg object-cover' alt='portfolio image 1' src={action1}/></div>
              <div><Image width={parseFloat('500%')} height={parseFloat('500%')} className='rounded-lg object-cover' alt='portfolio image 1' src={action2}/></div>
              <div><Image width={parseFloat('500%')} height={parseFloat('500%')} className='rounded-lg object-cover' alt='portfolio image 1' src={action3}/></div>
              <div><Image width={parseFloat('500%')} height={parseFloat('500%')} className='rounded-lg object-cover' alt='portfolio image 1' src={headshot1}/></div>
            </div>
          </section>

          <section>
            <div>
              <h3 className='text-3xl text-white py-1'>Services I Offer</h3>
              <p className='text-md py-2 leading-8 text-white dark:text-white'>We specialize in custom web development for small businesses and startups. Whether you need a simple brochure website or a complex web application, we have the expertise to bring your ideas to life.</p>
            </div>
            <div className='lg:flex gap-10'>
              <div className="text-center shadow-lg p-10 rounded-xl my-10 lg:mx-auto">
                <Image alt='3d icon of mountains' className='mx-auto' src={design} width={100} height={100}/>
                <h3 className='text-lg text-white font-medium pt-8 pb-2'>Beautiful Designs</h3>
                <p className='py-2 text-white'>Creating elegant designs suited for your needs.</p>
                <h4 className='py-4 text-red-400'>Design tools we use</h4>
                <p className='text-white dark:text-white py-1'>Figma</p>
                <p className='text-white dark:text-white py-1'>Photoshop</p>
                <p className='text-white dark:text-white py-1'>Illustrator</p>
              </div>
              <div className="text-center shadow-lg p-10 rounded-xl my-10 lg:mx-auto">
                <Image alt='hashtag symbol' className='mx-auto' src={code} width={100} height={100}/>
                <h3 className='text-lg text-white font-medium pt-8 pb-2'>Content Management System Integration</h3>
                <p className='py-2 text-white'>Organizing, updating and managing your content.</p>
                <h4 className='py-4 text-red-400'>CMS tools we use</h4>
                <p className='text-white dark:text-white py-1'>Wordpress</p>
                <p className='text-white dark:text-white py-1'>Drupal</p>
                <p className='text-white dark:text-white py-1'>Joomla</p>
              </div>
              <div className="text-center shadow-lg p-10 rounded-xl my-10 lg:mx-auto">
                <Image alt='thumbs up symbol' className='mx-auto' src={consulting} width={100} height={100}/>
                <h3 className='text-lg text-white font-medium pt-8 pb-2'>Maintenance and Support</h3>
                <p className='py-2 text-white'>Our availability and service.</p>
                <h4 className='py-4 text-red-400'>What type of support we provide.</h4>
                <p className='text-white dark:text-white py-1'>24 hour support</p>
                <p className='text-white dark:text-white py-1'>Contact via phone and email</p>
                <p className='text-white dark:text-white py-1'>One on one consultation</p>
              </div>
            </div>
          </section>

          <footer>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
              <a href="https://twitter.com/notjoshbomba" rel="noreferrer" target="_blank"><AiFillTwitterCircle /></a>
              <a href="https://www.linkedin.com/in/douglasmcgillivray/" rel="noreferrer" target="_blank"><AiFillLinkedin /></a>
              <a href="https://www.youtube.com/watch?v=Lvllkch4pU8" rel="noreferrer" target="_blank"><AiFillYoutube /></a>
            </div>
          </footer>
        </main>
      </>
    </div>
  )
}
